### ISSUE TITLE
[Feature Request] vue-i18n-loader for extracting all components' $t() key to JSON file

### ISSUE THREAD

**Issue by Emiya0306** [kazupon/vue-i18n-locale-message#1]
### What is Expected?
@kazupon There are many case that we need an i18n json manifest file which contains this project's i18n, and give it to our Project Manger for professional translation in a big project development process.

If we write the i18n in the component, we need to change all component i18n code for translation(maybe the PM will set down beside you and search which translation is not good or not done each time), I think it is not a good idea for development process.

So we should have this feature for better our life, it is the i18n extract.

```javascript
// for webpack config file
module.exports = {
  module: {
    rules: [{
      test: /\.vue$/,
      loader: 'vue',
      options: {
        loaders: {
          i18n: '@kazupon/vue-i18n-loader'
        },
        extract: true // new option to tell loader if we extract all components' i18n
        extractPath: './dist/i18n/[name].json' // i18n output location
      }
    }]
  }
}
```
Just like the webpack configuration above, it will be done.

### For static translation:
We should not write `<i18n>` or `locales` in *.vue files. Just write your `$t('userName')` in the code, and the loader will output the file automatically.

```javascript
{
  "en": {
    "userName": "userName" // maybe just output original string or on placeholder?
  },
  "jp": {
    "userName": "userName"
  }
}
```

If the translate has already changed, the output will not overwrite the value, just keep it.

### For dynamic translation (UPDATED):
Write your `$t(yourVariable, yourI18nList)`, and give the possible i18n key list, just like`var yourI18nList = ['your possible i18n key1', 'your possible i18n key2', 'and so on']`. And then, let it go!

**Comment by kazupon** [comment]
release out! vue-i18n-locale-message!
https://github.com/kazupon/vue-i18n-locale-message/releases/tag/v0.1.0
