### ISSUE TITLE
RFC: the output format

### ISSUE THREAD

**Issue by antfu** [kazupon/vue-i18n-locale-message#13]
The current output format uses nested objects to locate the file. While in this approach, the depth of the messaging content may changes. It's hard to tell which parts are file paths and which are actually messages **without looking through the file system again**.

I would recommend the following format

**Current**
```jsonc
{
  "ja": { // for `ja` locale`
    "App": { // src/App.vue
      "title": "アプリケーション",
      "lang": "言語切り替え"
    },
    "components": { // src/components
      "Modal": { // src/components/Modal.vue
        "ok": "OK",
        "cancel": "キャンセル"
      }
    },
    "pages": { // src/pages
      "Login": { // src/pages/Login.vue
        "id": "ユーザーID",
        "password": "パスワード",
        "confirm": "パスワードの確認入力",
        "button": "ログイン"
      }
    }
  },
  "en": { // for `en` locale
    "App": { // src/App.vue
      "title": "Application",
      "lang": "Change languages"
    },
    "components": { // src/components
      "Modal": { // src/components/Modal.vue
        "ok": "OK",
        "cancel": "Cancel"
      },
      "nest": { // src/components/nest
        "RankingTable": { // src/components/nest/RankingTable.vue
          "headers": {
            "rank": "Rank",
            "name": "Name",
            "score": "Score"
          }
        }
      }
    }
  }
}
```

**Proposed**

```jsonc
{
  "target": "/home/root/vue-i18n",
  // TODO: some other options passed to the tool, which may used for infusing

  "components": { // flat component paths
    "src/App.vue": [ // use array for mutliple i18n blocks
      {
        "lang": "json", // or "yaml", "json5"
        // TODO: some other block queries

        "messages": { // messages
          "ja": { // languages
            "title": "アプリケーション",
            "lang": "言語切り替え"
          },
          "en": {
            "title": "Application",
            "lang": "Change languages"
          }
        }
      }
    ],
    "src/components/Modal.vue": [
      {
        "lang": "yaml",
        "messages": {
          "ja": {
            "ok": "OK",
            "cancel": "キャンセル"
          }
        }
      }
    ]
  }
}
```

This propose may have following pros and cons:

**Pros:**
- Bilateral transform-able
- Components stay in a consistent location
- Allowing for representing multiple i18n blocks, #12 
- Keeps more information can be utilized by 3rd party tools

**Cons:**
- Can not directly used by `vue-i18n`
- A little more complex

----

Further more, there is also a proposal solution for overcome the problem introduced by this format:

![vue-i18n-format-proposal (1)](https://user-images.githubusercontent.com/11247099/64075128-e4855b00-cce6-11e9-9fe5-6703357214ba.png)

**Comment by kazupon** [comment]
Thank you for your RFC!
I like this idea!
It make sense!  👍 

This idea hard to handle JSON format directly at translation services, but it's awesome because it contains meta information that can be processed by third-party vendor tools.

I will further refine specifications the your RFC specifications that can be processed with the squeeze / infuse API.

**Comment by antfu** [comment]
Great work! 

May I have some docs about this? Thanks!

**Comment by kazupon** [comment]
OK!
Please wait for a little while longer. :pray:
